services:
  sheraton-rate-memcached:
    image: memcached:1.6
    container_name: "sheraton_rate_memcached"
    command: --port 11003
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  sheraton-rate-mongo:
    image: mongo:7.0
    container_name: "sheraton_rate_mongo"
    command: --port 27003
    network_mode: "host"
    restart: always
    volumes:
      - sheraton-rate:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  sheraton-profile-memcached:
    image: memcached:1.6
    container_name: "sheraton_profile_memcached"
    command: --port 11004
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  sheraton-profile-mongo:
    image: mongo:7.0
    container_name: "sheraton_profile_mongo"
    command: --port 27004
    network_mode: "host"
    restart: always
    volumes:
      - sheraton-profile:/data
    deploy:
      resources:
        limits:
          cpus: "4"

volumes:
  sheraton-rate:
  sheraton-profile:
