[package]
edition = "2021"
license = "MIT"
name = "synthetic"
publish = false
version = "0.1.0"

[[bin]]
name = "synthetic_client_bench"
path = "src/client/client_bench.rs"

[[bin]]
name = "synthetic_frontend"
path = "src/frontend/main.rs"

[[bin]]
name = "synthetic_child"
path = "src/child/main.rs"

[[bin]]
name = "validate_config"
path = "src/bin/validate_config.rs"

[features]
prio_global = ["masa/prio_global"]
prio_local = ["masa/prio_local"]
prio_local_perfect = ["masa/prio_local"]
prio_oldest = ["masa/prio_oldest"]

est_rms = ["masa/est_rms"]
est_hist = ["masa/est_hist"]

fifo = ["masa/fifo"]

early = ["masa/early"]
trace-queue = ["masa/trace-queue", "tonic/trace-queue"]

gcp = ["dep:prost-types", "tonic/tls"]
routeguide = [
	"dep:async-stream",
	"tokio-stream",
	"dep:rand",
	"dep:serde",
	"dep:serde_json",
]
reflection = ["dep:tonic-reflection"]
autoreload = ["tokio-stream/net", "dep:listenfd"]
health = ["dep:tonic-health"]
grpc-web = [
	"dep:tonic-web",
	"dep:bytes",
	"dep:http",
	"dep:hyper",
	"dep:tracing-subscriber",
	"dep:tower",
]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
hyper-warp = [
	"dep:either",
	"dep:tower",
	"dep:hyper",
	"dep:http",
	"dep:http-body",
	"dep:warp",
]
hyper-warp-multiplex = ["hyper-warp"]
uds = ["tokio-stream/net", "dep:tower", "dep:hyper"]
streaming = ["tokio-stream", "dep:h2"]
mock = ["tokio-stream", "dep:tower"]
tower = ["dep:hyper", "dep:tower", "dep:http"]
json-codec = ["dep:serde", "dep:serde_json", "dep:bytes"]
compression = ["tonic/gzip"]
tls = ["tonic/tls"]
tls-rustls = [
	"dep:hyper",
	"dep:hyper-rustls",
	"dep:tower",
	"tower-http/util",
	"tower-http/add-extension",
	"dep:rustls-pemfile",
	"dep:tokio-rustls",
]
dynamic-load-balance = ["dep:tower"]
timeout = ["tokio/time", "dep:tower"]
tls-client-auth = ["tonic/tls"]
types = ["dep:tonic-types"]
h2c = ["dep:hyper", "dep:tower", "dep:http"]
cancellation = ["dep:tokio-util"]

full = [
	"gcp",
	"routeguide",
	"reflection",
	"autoreload",
	"health",
	"grpc-web",
	"tracing",
	"hyper-warp",
	"hyper-warp-multiplex",
	"uds",
	"streaming",
	"mock",
	"tower",
	"json-codec",
	"compression",
	"tls",
	"tls-rustls",
	"dynamic-load-balance",
	"timeout",
	"tls-client-auth",
	"types",
	"cancellation",
	"h2c",
]
default = ["full"]

[dependencies]
# Reboot
masa = { path = "../../libs/masa" }
app-utils = { path = "../app-utils" }
app-util-macros = { path = "../app-util-macros" }
futures-lite = { version = "2.0.0" }
structopt = "0.3.23"
crossbeam-channel = "0.5"
mongodb = { version = "=2.8.2" }
memcache = "0.16"
async-memcached = "0.5.0"
log = "0.4"
# Common dependencies
tokio = { path = "../../libs/tokio/tokio", features = [
	"rt-multi-thread",
	"macros",
] }
prost = "0.12"
tonic = { path = "../../libs/tonic/tonic" }
futures = "0.3"
# Optional dependencies
tonic-web = { path = "../../libs/tonic/tonic-web", optional = true }
tonic-health = { path = "../../libs/tonic/tonic-health", optional = true }
tonic-reflection = { path = "../../libs/tonic/tonic-reflection", optional = true }
tonic-types = { path = "../../libs/tonic/tonic-types", optional = true }
either = { version = "1.9", optional = true }
async-stream = { version = "0.3", optional = true }
tokio-stream = { path = "../../libs/tokio/tokio-stream", optional = true }
tokio-util = { path = "../../libs/tokio/tokio-util", optional = true }
tower = { path = "../../libs/tower/tower", optional = true }
rand = { version = "0.8", optional = true }
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = [
	"tracing-log",
	"fmt",
], optional = true }
prost-types = { version = "0.12", optional = true }
http = { version = "0.2", optional = true }
http-body = { version = "0.4.2", optional = true }
hyper = { path = "../../libs/hyper", optional = true }
warp = { version = "0.3.4", default-features = false, optional = true }
listenfd = { version = "1.0", optional = true }
bytes = { version = "1", optional = true }
h2 = { version = "0.3.27", optional = true }
tokio-rustls = { version = "0.26.0", optional = true }
hyper-rustls = { version = "0.24.0", features = ["http2"], optional = true }
rustls-pemfile = { version = "1", optional = true }
tower-http = { version = "0.4", optional = true }
anyhow = "1.0"
geo = "0.28"
# used by the geo service
kiddo = "4.2.1"
# used by reservation service
chrono = "0.4.38"
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"


[build-dependencies]
tonic-build = { path = "../../libs/tonic/tonic-build", features = ["prost"] }
protoc-bin-vendored = "3"
