image: "rustlang/rust:nightly"

# Run on default branch as well as on merge requests
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Define stages
stages:
  - fmt
  - check
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -y protobuf-compiler

include:
  - local: /.gitlab/fmt-cargo.yml
  - local: /.gitlab/check-cargo.yml
  - local: /.gitlab/test-cargo.yml
  - local: /.gitlab/test-e2e-hotel.yml
