[workspace]
members = [
  "tonic",
  "tonic-build",
  "tonic-health",
  "tonic-types",
  "tonic-reflection",
  "tonic-web",        # Non-published crates
  "tonic-masa",
  "examples",
  "reboot-hotel",
  # socialnetwork eval impl
  "reboot-socialnet/unique_id",
  "codegen",
  "interop",                          # Tests
  "tests/disable_comments",
  "tests/included_service",
  "tests/same_name",
  "tests/service_named_service",
  "tests/wellknown",
  "tests/wellknown-compiled",
  "tests/extern_path/uuid",
  "tests/ambiguous_methods",
  "tests/extern_path/my_application",
  "tests/integration_tests",
  "tests/masa_integration_tests",
  "tests/stream_conflict",
  "tests/root-crate-path",
  "tests/compression",
  "tonic-web/tests/integration",
  "tests/service_named_result",
  "tests/use_arc_self",
  "tests/default_stubs",
]
resolver = "2"

[profile.release]
debug = true
# Disable name mangling
debug-assertions = false
# lto = false
# codegen-units = 1
opt-level = 3


[patch.crates-io]
# rewrite dependencies to use the our version of async-task when running tests
async-task = { path = "./3rd_party/async-task" }
trust-dns-resolver = { path = "./3rd_party/trust-dns/crates/resolver" }
tokio = { path = "./3rd_party/tokio/tokio", version = "1" }

