[workspace]
members = [
  # tonic
  "libs/tonic/tonic",
  "libs/tonic/tonic-build",
  "libs/tonic/tonic-health",
  "libs/tonic/tonic-types",
  "libs/tonic/tonic-reflection",
  "libs/tonic/tonic-web",
  "libs/tonic/examples",
  "libs/tonic/codegen",
  "libs/tonic/interop",
  "libs/tonic/tests/disable_comments",
  "libs/tonic/tests/included_service",
  "libs/tonic/tests/same_name",
  "libs/tonic/tests/service_named_service",
  "libs/tonic/tests/wellknown",
  "libs/tonic/tests/wellknown-compiled",
  "libs/tonic/tests/extern_path/uuid",
  "libs/tonic/tests/ambiguous_methods",
  "libs/tonic/tests/extern_path/my_application",
  "libs/tonic/tests/integration_tests",
  "libs/tonic/tests/masa_integration_tests",
  "libs/tonic/tests/stream_conflict",
  "libs/tonic/tests/root-crate-path",
  "libs/tonic/tests/compression",
  "libs/tonic/tonic-web/tests/integration",
  "libs/tonic/tests/service_named_result",
  "libs/tonic/tests/use_arc_self",
  "libs/tonic/tests/default_stubs",
  # masa support
  "libs/masa",

  # evaluation applications
  "apps/hotel",
  "apps/socialnet",
  "apps/synthetic",
  "apps/mssim/generic-service",
  "apps/mssim/sim-config",
  "apps/app-utils",
  "apps/app-util-macros",
  "apps/benchmark",
]
resolver = "2"

[profile.release]
debug = true
# Disable name mangling
debug-assertions = false
# lto = false
# codegen-units = 1
opt-level = 3


[patch.crates-io]
tokio = { path = "./libs/tokio/tokio", version = "1" }
hyper = { path = "./libs/hyper" }
tower-service = { path = "./libs/tower/tower-service" }
tower-layer = { path = "./libs/tower/tower-layer" }
tower = { path = "./libs/tower/tower" }
tokio-util = { path = "./libs/tokio/tokio-util" }
tokio-stream = { path = "./libs/tokio/tokio-stream" }
tokio-test = { path = "./libs/tokio/tokio-test" }
tokio-macros = { path = "./libs/tokio/tokio-macros" }
