"""
MSSIM (microservice simulator) application plugin for the experiment runner.

MSSIM differs from the default runner flow:
- It generates a docker-compose.yml per (policy, rps, repeat) via `python -m simulator.main`
- It runs the workload via `docker compose up --abort-on-container-exit`
- It always cleans up with `docker compose down --volumes`
"""

from __future__ import annotations

import csv
import hashlib
import json
import logging
import os
import re
import subprocess
import sys
import threading
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..config import ExperimentConfig
    from ..deployment_manager import DeploymentManager as DockerManager
import time
from pathlib import Path
from typing import Optional

# Import MSSIM constants for container/service naming
from apps.mssim.simulator.orchestrator import LOADGEN_SERVICE_NAME

from ..cpu_monitor import CPUMonitor
from .base import AppBuilder, AppPlugin, DockerConfig, LoadGenerator
from .utils import normalize_features_to_tag

logger = logging.getLogger(__name__)

GENERIC_SERVICE_IMAGE = "generic_service"
MSSIM_LOADGEN_IMAGE = "mssim_load_generator"


def _canonicalize_features_for_build(feature: str) -> str:
    """
    Canonicalize features for use in build args (FEATURE_ARG).
    Returns comma-separated, sorted, deduplicated feature string.
    """
    parts = [part.strip() for part in re.split(r"[\s,]+", feature) if part.strip()]
    if not parts:
        return "default"
    return ",".join(sorted(set(parts)))


def _generic_service_image_for_policy(policy: str) -> str:
    """
    Get the docker image name for a given policy/features.
    Uses normalized feature flags for tagging like other apps in exp_runner.runner.
    """
    tag = normalize_features_to_tag(policy)
    return f"{GENERIC_SERVICE_IMAGE}:{tag}"


def _safe_project_name(
    *, experiment_name: str, iteration: int, policy: str, rps: float
) -> str:
    # docker compose project names should be simple; use a digest for uniqueness.
    raw = f"{experiment_name}|{iteration}|{policy}|{rps}"
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:12]
    slug = re.sub(r"[^a-z0-9]+", "-", experiment_name.lower()).strip("-")[:24] or "exp"
    return f"mssim-{slug}-{digest}"


def _is_load_generator_container(container_name: str) -> bool:
    """
    Check if a container name corresponds to the load generator container.

    Docker Compose generates container names as {project_name}-{service_name}-{index},
    so we check if the service name appears in the container name.

    Args:
        container_name: The container name to check

    Returns:
        True if the container is the load generator, False otherwise
    """
    name_lower = container_name.lower()
    return LOADGEN_SERVICE_NAME in name_lower or "loadgen" in name_lower


class MssimLoadGenerator(LoadGenerator):
    """
    Placeholder load generator.

    MSSIM runs the load generator as part of the generated docker-compose stack,
    so the default LoadGenerator.run() flow is not used. This class exists only
    to satisfy the abstract interface requirements.

    WARNING: Do not call run() on this class. MSSIM uses docker-compose to manage
    containers, and container names are dynamically generated as
    {project_name}-load_generator-1.
    """

    def get_container_name(self) -> str:
        """
        Return a placeholder container name.

        WARNING: This method should not be used for MSSIM. Container names are
        dynamically generated by docker-compose as {project_name}-load_generator-1.
        This method exists only to satisfy the abstract interface.

        Raises:
            NotImplementedError: If called, since MSSIM doesn't use this flow
        """
        raise NotImplementedError(
            "MssimLoadGenerator.get_container_name() should not be called. "
            "MSSIM uses docker-compose with dynamically named containers. "
            "Use _is_load_generator_container() to identify load generator containers."
        )

    def get_network_name(self) -> str:
        return "mssim_network"

    def get_image_name(self) -> str:
        return MSSIM_LOADGEN_IMAGE

    def get_binary_name(self) -> str:
        return "mssim_load_generator"


class MssimBuilder(AppBuilder):
    """
    Build logic for MSSIM images.

    - Always builds mssim_load_generator once per runner invocation.
    - Builds a policy-specific generic service image (with deterministic tag) and also tags it
      as `generic_service` for compatibility.
    """

    def __init__(self) -> None:
        self._loadgen_built = False
        self._built_feature_keys: set[str] = set()

    def build(
        self,
        *,
        repo_root: Path,
        app_dir: Path,
        features: Optional[str] = None,
        rust_log: str = "info",
        no_cache: bool = False,
        gen_config_path: Optional[Path] = None,
        dry_run: bool = False,
    ) -> Optional[list[list[str]]]:
        # NOTE: rust_log/app_config_path/gen_config_path are unused for MSSIM builds today.
        commands: list[list[str]] = []

        # Start timing the docker build
        build_start_time = time.time()

        dockerfile = repo_root / "apps" / "mssim" / "generic-service" / "Dockerfile"
        if not dockerfile.exists():
            raise FileNotFoundError(f"MSSIM dockerfile not found: {dockerfile}")

        # Build load generator image once
        if not self._loadgen_built:
            # Use a unique cache ID to avoid race conditions in parallel builds
            # Use "mssim-loadgen" as a consistent cache ID for the loadgen build
            loadgen_cache_id = "mssim-loadgen"
            loadgen_cmd = [
                "docker",
                "buildx",
                "build",
                "--load",
                "-t",
                MSSIM_LOADGEN_IMAGE,
                "--target",
                "loadgen",
                "--build-arg",
                f"CACHE_ID={loadgen_cache_id}",
                "-f",
                str(dockerfile),
                str(repo_root),
            ]
            if no_cache:
                loadgen_cmd.insert(-1, "--no-cache")

            if dry_run:
                commands.append(loadgen_cmd)
            else:
                subprocess.run(loadgen_cmd, cwd=repo_root, check=True)

            self._loadgen_built = True

        # Build generic service image for policy/features
        policy = (features or "").strip() or "default"
        # Use normalized tag for image tagging (consistent with other apps)
        tag = normalize_features_to_tag(policy)
        # Canonicalize features for build arg (sort, deduplicate)
        features_for_build = _canonicalize_features_for_build(policy)

        if tag not in self._built_feature_keys:
            feature_image = _generic_service_image_for_policy(policy)
            # Use a unique cache ID based on features to avoid race conditions in parallel builds
            # Format: mssim-{tag} to match the pattern used by other apps
            cache_id = f"mssim-{tag}"

            generic_cmd = [
                "docker",
                "buildx",
                "build",
                "--load",
                "-t",
                feature_image,
                "--build-arg",
                f"FEATURE_ARG={features_for_build}",
                "--build-arg",
                f"CACHE_ID={cache_id}",
                "--target",
                "generic-service",
                "-f",
                str(dockerfile),
                str(repo_root),
            ]
            if no_cache:
                generic_cmd.insert(-1, "--no-cache")

            tag_cmd = ["docker", "tag", feature_image, GENERIC_SERVICE_IMAGE]

            if dry_run:
                commands.append(generic_cmd)
                commands.append(tag_cmd)
            else:
                subprocess.run(generic_cmd, cwd=repo_root, check=True)
                subprocess.run(tag_cmd, cwd=repo_root, check=True)

            self._built_feature_keys.add(tag)

        if not dry_run:
            # Calculate and print build duration
            build_duration = time.time() - build_start_time
            logger.info(
                f"Docker image building took {build_duration:.2f} seconds ({build_duration / 60:.2f} minutes)"
            )

        return commands if dry_run else None


class MssimApp(AppPlugin):
    def __init__(self) -> None:
        self._builder = MssimBuilder()

    def get_app_name(self) -> str:
        return "mssim"

    def get_required_gen_config_fields(self) -> list[str]:
        # MSSIM needs repeats and RPS sweep values.
        return ["Repeats", "Rps"]

    def load_app_config(self, config_path: Path) -> dict:
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def generate_env_vars(
        self,
        gen_config: dict,
        app_config: Optional[dict],
        app_dir: Path,
    ) -> dict:
        # MSSIM env vars are interpreted by the generated docker-compose stack.
        cfg = app_config or {}
        env: dict[str, str] = {}

        env["SLO_MS"] = str(int(cfg["slo_ms"]))
        env["ORCHESTRATOR"] = str(cfg.get("orchestrator", "localhost:50051"))

        duration = int(gen_config.get("DurationSecs", 0) or 0)
        warmup = int(gen_config.get("WarmupSecs", 0) or 0)
        if duration > 0:
            env["DURATION"] = str(duration)
        if warmup > 0:
            env["WARMUP_SEC"] = str(warmup)

        max_in_flight = gen_config.get("MaxInFlight")
        if max_in_flight is not None:
            env["MAX_IN_FLIGHT"] = str(int(max_in_flight))

        stats_interval = cfg.get("stats_interval_sec")
        if stats_interval is not None and int(stats_interval) > 0:
            env["STATS_INTERVAL_SEC"] = str(int(stats_interval))

        replay_path = cfg.get("replay_path")
        if replay_path:
            env["REPLAY_TRACE_PATH"] = str(Path(replay_path).expanduser().resolve())

        extra_env = cfg.get("extra_env") or {}
        for k, v in extra_env.items():
            env[str(k)] = str(v)

        return env

    def get_docker_config(self) -> DockerConfig:
        # compose_file is unused for MSSIM (it is generated per run).
        return DockerConfig(
            compose_file="generated",
            network_name="mssim_network",
            loadgen_image_name=MSSIM_LOADGEN_IMAGE,
            loadgen_binary_name="mssim_load_generator",
            app_config_filename="mssim.json",
        )

    def get_container_names(self, env_vars: dict) -> list[str]:
        # MSSIM logs are captured via orchestrator.log rather than docker logs streaming.
        return []

    def prepare_workload(
        self,
        config: "ExperimentConfig",
        policy: str,
        iteration: int,
        output_dir: Path,
        repo_root: Path,
        use_k8s: bool = False,
    ) -> dict:
        """
        Prepare workload configuration.
        For MSSIM, this is handled inside run_workload currently.
        """
        # This is a stub to satisfy ABC.
        return {}

    def get_deployment_location(
        self, output_dir: Path, use_k8s: bool, repo_root: Path
    ) -> tuple[Path, str]:
        """
        Get deployment location.
        """
        # This is a stub to satisfy ABC.
        # MSSIM generates docker-compose.yml in the run directory.
        return output_dir, "docker-compose.yml"

    def get_loadgen_spec(
        self,
        output_dir: Path,
        features: Optional[str],
        env_vars: dict,
        use_k8s: bool,
    ) -> TaskSpec:
        """
        Get load generator spec.
        """
        # This is a stub. MSSIM runs loadgen as part of the compose stack.
        from ..deployment_manager import TaskSpec

        return TaskSpec(
            name="mssim-loadgen-stub",
            image="mssim_load_generator",
            env_vars={},
        )

    def create_load_generator(self, features: Optional[str] = None) -> LoadGenerator:
        return MssimLoadGenerator()

    def create_builder(self) -> AppBuilder:
        return self._builder

    def verify_results(self, config: "ExperimentConfig") -> bool:
        """
        Verification logic for MSSIM.
        Checks for presence of metadata and latency files, and validates goodput.
        """
        logger.info(f"Verifying MSSIM experiment: {config.experiment_name}")

        gen_config = config.gen_config
        try:
            rps_list = gen_config["Rps"]
            repeats = gen_config.get("Repeats", 1)
            duration = gen_config["DurationSecs"]
        except KeyError as e:
            logger.error(f"Missing key in gen_config.json: {e}")
            return False

        policies = config.policies
        run_id = "run_0"

        # Check done marker
        done_file = config.out_dir / "done"
        if not done_file.exists():
            logger.error(f"Experiment not marked as complete: {done_file} missing")
            return False

        all_passed = True

        for i in range(repeats):
            for policy in policies:
                # MSSIM structure: {out_dir}/{iteration}/{policy}/run_0/
                policy_run_dir = config.out_dir / str(i) / policy / run_id
                if not policy_run_dir.exists():
                    logger.error(
                        f"MSSIM policy run directory missing: {policy_run_dir}"
                    )
                    all_passed = False
                    continue

                if not (policy_run_dir / "metadata.json").exists():
                    logger.error(
                        f"MSSIM metadata.json missing: {policy_run_dir / 'metadata.json'}"
                    )
                    all_passed = False

                for rps in rps_list:
                    # Look for standard format files first: r{rps}_{api}.csv
                    # Note: RPS in filename might be formatted (e.g. 100 or 100_5)
                    # We use glob to find matching files
                    latency_files = list(policy_run_dir.glob(f"r{int(rps)}_*.csv"))

                    # Fallback to legacy format
                    if not latency_files:
                        legacy_file = (
                            policy_run_dir / f"root_latencies_{int(rps)}rps.csv"
                        )
                        if legacy_file.exists():
                            latency_files = [legacy_file]

                    if not latency_files:
                        logger.error(
                            f"MSSIM latency files missing for {rps} RPS in {policy_run_dir}"
                        )
                        all_passed = False
                        continue

                    # Calculate goodput across all files for this RPS
                    current_rps_goodput = 0
                    for latency_file in latency_files:
                        try:
                            with open(latency_file, "r") as f:
                                reader = csv.reader(f)
                                header = next(reader, None)
                                if not header:
                                    continue

                                # Find error column index
                                try:
                                    error_idx = header.index("error")
                                except ValueError:
                                    # Fallback for legacy files without header or different names
                                    # Legacy format: error is at index 6
                                    error_idx = 6

                                for row in reader:
                                    if len(row) > error_idx:
                                        error = row[error_idx].strip()
                                        if error == "/None":
                                            current_rps_goodput += 1
                        except Exception as e:
                            logger.error(
                                f"Failed to read MSSIM CSV {latency_file}: {e}"
                            )
                            all_passed = False
                            continue

                    expected_total = rps * duration
                    lower = expected_total * 0.8
                    upper = expected_total * 1.2

                    if not (lower <= current_rps_goodput <= upper):
                        observed_rps = current_rps_goodput / duration
                        logger.error(
                            f"Goodput mismatch for {rps} RPS (Policy: {policy}, Iteration: {i})\n"
                            f"  Expected: ~{expected_total:.0f} (+/- 20%)\n"
                            f"  Got: {current_rps_goodput}\n"
                            f"  Observed RPS: {observed_rps:.2f} (Target: {rps:.2f})"
                        )
                        all_passed = False

        return all_passed

    def run_workload(
        self,
        *,
        repo_root: Path,
        config: "ExperimentConfig",
        deployment: "DockerManager",
        policy: str,
        iteration: int,
        output_dir: Path,
        app_local_dir: Path,
        no_cache: bool,
        dry_run: bool = False,
        **kwargs,
    ) -> None:
        """Run mssim experiment."""
        if type(deployment).__name__ == "K8sManager":
            raise NotImplementedError(
                "Mssim app does not support Kubernetes execution yet"
            )
        # MSSIM-specific orchestration:
        # - build images (cached across calls)
        # - generate compose once and run all RPS levels in a single docker-compose session
        mssim_cfg = config.app_config or {}

        # Handle callgraph_dirs as list
        callgraph_dirs_raw = mssim_cfg.get("callgraph_dirs")
        if callgraph_dirs_raw is None:
            raise ValueError(
                "mssim.json must include 'callgraph_dirs' (list of call graph directory paths)"
            )

        if not isinstance(callgraph_dirs_raw, list):
            raise ValueError("'callgraph_dirs' must be a list of directory paths")

        if len(callgraph_dirs_raw) == 0:
            raise ValueError(
                "'callgraph_dirs' must contain at least one directory path"
            )

        callgraph_dirs = [Path(d).expanduser().resolve() for d in callgraph_dirs_raw]
        for callgraph_dir in callgraph_dirs:
            if not callgraph_dir.exists():
                raise FileNotFoundError(
                    f"MSSIM callgraph_dir does not exist: {callgraph_dir}"
                )

        # Look for replicas.json in the experiment input directory
        replicas_path = config.in_dir / "replicas.json"
        if not replicas_path.exists():
            replicas_path = None  # Default to 1 replica per service

        rps_values = [float(v) for v in (config.gen_config.get("Rps") or [])]
        if not rps_values:
            raise ValueError("gen_config.json must include non-empty 'Rps' for MSSIM")

        duration_sec = int(config.gen_config.get("DurationSecs", 0) or 0)

        # Build images (dry-run prints build commands)
        builder = self.create_builder()
        build_cmds = builder.build(
            repo_root=repo_root,
            app_dir=config.app_dir,
            features=policy,
            rust_log="info",
            no_cache=no_cache,
            gen_config_path=(config.in_dir / "gen_config.json"),
            dry_run=dry_run,
        )
        if dry_run and build_cmds:
            print("\n".join(" ".join(cmd) for cmd in build_cmds))

        # Base environment variables for MSSIM stack
        base_env_vars = self.generate_env_vars(
            config.gen_config, config.app_config, config.app_dir
        )

        # Use a single run directory for all RPS values
        run_dir = output_dir / f"run_{iteration:01d}"
        docker_compose_path = run_dir / "docker-compose.yml"
        deployment_json_path = run_dir / "deployment.json"
        log_path = run_dir / "orchestrator.log"

        feature_image = _generic_service_image_for_policy(policy)

        env = os.environ.copy()
        env.update({k: str(v) for k, v in base_env_vars.items()})
        env["FEATURE"] = str(policy)
        # Pass all RPS values as JSON array
        env["RPS_VALUES"] = json.dumps(rps_values)
        env["SLO_MS"] = str(int(mssim_cfg["slo_ms"]))
        env["GENERIC_SERVICE_IMAGE"] = feature_image
        env["HOST_TRACE_DIR"] = str(run_dir.resolve())

        project_name = _safe_project_name(
            experiment_name=config.experiment_name,
            iteration=iteration,
            policy=policy,
            rps=0.0,  # Use 0.0 as placeholder since we're running all RPS in one go
        )
        env["DOCKER_COMPOSE_PROJECT_NAME"] = project_name

        trace_cmd = [
            sys.executable,
            "-m",
            "simulator.main",
            "--docker-compose-output-path",
            str(docker_compose_path),
            "--deployment-output-path",
            str(deployment_json_path),
        ]
        # Add all callgraph directories
        for callgraph_dir in callgraph_dirs:
            trace_cmd.extend(["-a", str(callgraph_dir)])
        if replicas_path is not None:
            trace_cmd.extend(["--replicas-path", str(replicas_path)])
        if mssim_cfg.get("replay_path"):
            trace_cmd.extend(
                [
                    "--replay-path",
                    str(Path(mssim_cfg["replay_path"]).expanduser().resolve()),
                ]
            )

        up_cmd = [
            "docker",
            "compose",
            "-f",
            str(docker_compose_path),
            "-p",
            project_name,
            "up",
            "-d",  # Start in detached mode so we can stream individual logs
        ]
        down_cmd = [
            "docker",
            "compose",
            "-f",
            str(docker_compose_path),
            "-p",
            project_name,
            "down",
            "--volumes",
        ]

        if dry_run:
            print(
                f"[dry-run] would run mssim policy={policy} rps_values={rps_values} iteration={iteration}"
            )
            print(f"[dry-run] would write outputs under: {run_dir}")
            print("[dry-run] compose generation:", " ".join(trace_cmd))
            print("[dry-run] compose up:", " ".join(up_cmd))
            print("[dry-run] compose down:", " ".join(down_cmd))
            return

        run_dir.mkdir(parents=True, exist_ok=True)
        metadata = {
            "app": "mssim",
            "experiment": config.experiment_name,
            "iteration": iteration,
            "policy": policy,
            "rps_values": rps_values,
            "duration_sec": duration_sec,
            "callgraph_dirs": [str(d) for d in callgraph_dirs],
            "replicas_path": str(replicas_path) if replicas_path is not None else None,
            "generic_service_image": feature_image,
            "docker_project": project_name,
        }
        with (run_dir / "metadata.json").open("w", encoding="utf-8") as fh:
            json.dump(metadata, fh, indent=2, sort_keys=True)

        # Initialize CPU monitor with project name filter
        cpu_stats_file = run_dir / "cpu_stats.csv"
        cpu_monitor = CPUMonitor(
            output_path=cpu_stats_file, poll_interval=2.0, container_prefix=project_name
        )

        log_threads: list[threading.Thread] = []
        try:
            # Generate compose/deployment once
            with log_path.open("wb") as log_file:
                gen_proc = subprocess.run(
                    trace_cmd,
                    cwd=config.app_dir,
                    env=env,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                )
            if gen_proc.returncode != 0:
                raise RuntimeError(
                    f"MSSIM compose generation failed ({gen_proc.returncode}). See log at {log_path}"
                )

            # Run the experiment stack in detached mode
            print(
                f"Starting services for policy={policy} rps_values={rps_values} iteration={iteration}"
            )
            deployment.start(
                app_dir=run_dir,
                deployment_config="docker-compose.yml",
                env_vars=env,
                project_name=project_name,
            )

            # Wait a moment for containers to start
            time.sleep(2)

            # Start CPU monitoring after services are up
            cpu_monitor.start()

            # Get container names and stream logs to individual files
            logs_dir = run_dir / "logs"
            # Get container names for log streaming
            container_names = deployment.get_container_names(
                config_path=docker_compose_path,
                project_name=project_name,
                env_vars=env,
            )

            if container_names:
                print(
                    f"Streaming logs for {len(container_names)} containers to {logs_dir}"
                )
                log_threads = deployment.stream_logs(
                    container_names=container_names,
                    output_dir=logs_dir,
                    follow=True,
                )
            else:
                print("Warning: No containers found for log streaming")

            # Wait for load generator to exit (it will run all RPS levels)
            loadgen_container = None
            for name in container_names:
                if _is_load_generator_container(name):
                    loadgen_container = name
                    break

            if loadgen_container:
                # Calculate total timeout: duration per RPS level + grace period
                grace_period = 300
                total_duration = (
                    duration_sec * len(rps_values) if duration_sec > 0 else 0
                )
                timeout = total_duration + grace_period if total_duration > 0 else None
                start_time = time.time()

                while True:
                    # Check if load generator container has exited
                    check_cmd = [
                        "docker",
                        "inspect",
                        "--format={{.State.Status}}",
                        loadgen_container,
                    ]
                    try:
                        result = subprocess.run(
                            check_cmd,
                            capture_output=True,
                            text=True,
                            check=True,
                        )
                        status = result.stdout.strip()
                        if status == "exited":
                            break
                    except subprocess.CalledProcessError:
                        # Container might not exist yet, wait a bit
                        pass

                    if timeout and (time.time() - start_time) > timeout:
                        raise RuntimeError(
                            f"MSSIM timeout expired after {total_duration} (+{grace_period}) seconds"
                        )

                    time.sleep(1)
            else:
                # Fallback: wait for total duration if no load generator found
                total_duration = (
                    duration_sec * len(rps_values) if duration_sec > 0 else 0
                )
                if total_duration > 0:
                    print(
                        f"Waiting {total_duration} seconds for experiment to complete"
                    )
                    time.sleep(total_duration)

        except RuntimeError:
            # Re-raise RuntimeErrors (including timeout)
            raise
        except Exception as exc:
            raise RuntimeError(f"MSSIM experiment failed: {exc}") from exc
        finally:
            # Stop CPU monitoring before stopping services
            try:
                cpu_monitor.stop()
            except Exception as e:
                logger.warning(f"Error stopping CPU monitor: {e}")

            deployment.stop(
                app_dir=run_dir,
                deployment_config="docker-compose.yml",
                env_vars=env,
                project_name=project_name,
            )

            # Wait for log threads to finish (they should stop when containers stop)
            for thread in log_threads:
                thread.join(timeout=5)
