//! Async Rust port of the C++ Write-Home-Timeline Service.
//!
//! This application listens to a RabbitMQ queue for new posts, fetches the
//! author's followers from a social graph gRPC service, and then writes the post
//! into the Redis-based home timeline for each follower.
//!
//! It uses the Tokio runtime for async operations, `lapin` for RabbitMQ,
//! `redis-rs` for Redis, `bb8` for connection pooling, and `tonic` for gRPC.

use anyhow::{Context, Result};
use std::sync::Arc;
use tokio::task::JoinHandle;
use tracing::{error, info, Level};
use tracing_subscriber::FmtSubscriber;

use crate::worker::run_worker;

// This line includes the Rust code generated by tonic-build from social_graph.proto.
// The string "social_graph" must match the package name in the .proto file.
pub mod social_graph {
    tonic::include_proto!("social_graph");
}

use crate::social_graph::social_graph_service_client::SocialGraphServiceClient;
use crate::social_graph::GetFollowersRequest;
use tonic::transport::Channel;

// Type aliases for our connection pools for easier use.
pub type RedisPool = bb8::Pool<bb8_redis::RedisConnectionManager>;
pub type SocialGraphPool = bb8::Pool<social_graph_client::SocialGraphConnectionManager>;

/// Configuration module to load and manage application settings.
mod config {
    use config::{Config, ConfigError, File};
    use serde::Deserialize;

    #[derive(Debug, Deserialize, Clone)]
    pub struct ServiceConfig {
        pub workers: usize,
    }

    #[derive(Debug, Deserialize, Clone)]
    pub struct RabbitMQConfig {
        pub addr: String,
        pub port: u16,
    }

    #[derive(Debug, Deserialize, Clone)]
    pub struct RedisConfig {
        pub addr: String,
        pub port: u16,
        pub connections: u32,
    }

    #[derive(Debug, Deserialize, Clone)]
    pub struct SocialGraphServiceConfig {
        pub addr: String,
        pub port: u16,
        pub connections: u32,
    }

    #[derive(Debug, Deserialize, Clone)]
    pub struct AppConfig {
        #[serde(rename = "write-home-timeline-service")]
        pub service: ServiceConfig,
        #[serde(rename = "write-home-timeline-rabbitmq")]
        pub rabbitmq: RabbitMQConfig,
        #[serde(rename = "home-timeline-redis")]
        pub redis: RedisConfig,
        #[serde(rename = "social-graph-service")]
        pub social_graph_service: SocialGraphServiceConfig,
    }

    /// Loads configuration from the specified file path.
    pub fn load_config() -> Result<AppConfig, ConfigError> {
        let builder = Config::builder().add_source(File::with_name("config/service-config.json"));
        builder.build()?.try_deserialize()
    }
}

/// Module for the Social Graph Service gRPC client and connection manager.
mod social_graph_client {
    use super::{Channel, SocialGraphServiceClient};
    use anyhow::{anyhow, Result};

    use tonic::transport::Endpoint;

    #[derive(Debug)]
    pub struct MyError(pub anyhow::Error);

    impl std::fmt::Display for MyError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            self.0.fmt(f)
        }
    }

    impl std::error::Error for MyError {
        fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
            self.0.source()
        }
    }

    /// A connection manager for `bb8` to create and manage SocialGraphServiceClient instances.
    #[derive(Clone, Debug)]
    pub struct SocialGraphConnectionManager {
        pub addr: String,
    }

    impl bb8::ManageConnection for SocialGraphConnectionManager {
        type Connection = SocialGraphServiceClient<Channel>;
        type Error = MyError;

        async fn connect(&self) -> Result<Self::Connection, Self::Error> {
            let channel = Endpoint::from_shared(self.addr.clone())
                .map_err(|e| MyError(anyhow!(e)))?
                .connect()
                .await
                .map_err(|e| {
                    MyError(anyhow!("Failed to connect to Social Graph Service: {}", e))
                })?;

            Ok(SocialGraphServiceClient::new(channel))
        }

        async fn is_valid(&self, _conn: &mut Self::Connection) -> Result<(), Self::Error> {
            // Tonic clients handle their own connection state. For a production system,
            // you might add a gRPC health check endpoint and call it here.
            Ok(())
        }

        fn has_broken(&self, _conn: &mut Self::Connection) -> bool {
            // Tonic's connection management is robust. We rely on calls failing
            // to detect a broken connection, which bb8 will then handle.
            false
        }
    }
}

/// Worker module containing the core logic for processing RabbitMQ messages.
mod worker {
    use super::{GetFollowersRequest, RedisPool, SocialGraphPool};
    use anyhow::{anyhow, Context, Result};
    use futures_lite::stream::StreamExt;
    use lapin::{
        options::{BasicAckOptions, BasicConsumeOptions, BasicNackOptions, QueueDeclareOptions},
        types::FieldTable,
        Connection, ConnectionProperties,
    };

    use serde::Deserialize;
    use std::{collections::HashSet, sync::Arc};
    use tracing::{debug, error, info, warn};

    const QUEUE_NAME: &str = "write-home-timeline";

    #[derive(Debug, Deserialize)]
    struct PostMessage {
        user_id: i64,
        post_id: i64,
        timestamp: i64,
        user_mentions_id: Vec<i64>,
    }

    pub async fn run_worker(
        worker_id: usize,
        config: Arc<super::config::AppConfig>,
        redis_pool: RedisPool,
        social_graph_pool: SocialGraphPool,
    ) -> Result<()> {
        let rabbit_addr = format!(
            "amqp://guest:guest@{}:{}/%2f",
            config.rabbitmq.addr, config.rabbitmq.port
        );

        info!(worker_id, "Connecting to RabbitMQ at {}", rabbit_addr);
        let conn = Connection::connect(&rabbit_addr, ConnectionProperties::default())
            .await
            .context("Failed to connect to RabbitMQ")?;
        let channel = conn
            .create_channel()
            .await
            .context("Failed to create channel")?;

        channel
            .queue_declare(
                QUEUE_NAME,
                QueueDeclareOptions {
                    durable: true,
                    ..Default::default()
                },
                FieldTable::default(),
            )
            .await
            .context("Failed to declare queue")?;

        info!(
            worker_id,
            "Queue '{}' declared. Starting consumption.", QUEUE_NAME
        );

        let mut consumer = channel
            .basic_consume(
                QUEUE_NAME,
                &format!("worker-{}", worker_id),
                BasicConsumeOptions::default(),
                FieldTable::default(),
            )
            .await?;

        while let Some(delivery_result) = consumer.next().await {
            let delivery = match delivery_result {
                Ok(d) => d,
                Err(e) => {
                    error!(worker_id, "Error in message delivery: {}", e);
                    continue;
                }
            };

            let redis_clone = redis_pool.clone();
            let social_graph_clone = social_graph_pool.clone();
            let channel_clone = channel.clone();

            tokio::spawn(async move {
                let delivery_tag = delivery.delivery_tag;
                match process_message(&delivery.data, redis_clone, social_graph_clone).await {
                    Ok(_) => {
                        if let Err(e) = channel_clone
                            .basic_ack(delivery_tag, BasicAckOptions::default())
                            .await
                        {
                            error!("Failed to ACK message {}: {}", delivery_tag, e);
                        }
                    }
                    Err(e) => {
                        error!("Failed to process message {}: {:?}", delivery_tag, e);
                        if let Err(e) = channel_clone
                            .basic_nack(
                                delivery_tag,
                                BasicNackOptions {
                                    requeue: true,
                                    ..Default::default()
                                },
                            )
                            .await
                        {
                            error!("Failed to NACK message {}: {}", delivery_tag, e);
                        }
                    }
                }
            });
        }
        Ok(())
    }

    async fn process_message(
        data: &[u8],
        redis_pool: RedisPool,
        social_graph_pool: SocialGraphPool,
    ) -> Result<()> {
        let msg: PostMessage =
            serde_json::from_slice(data).context("Failed to parse message JSON")?;

        debug!("Processing message for user_id: {}", msg.user_id);

        // 1. Get followers from the social graph service.
        let mut social_graph_conn = social_graph_pool
            .get()
            .await
            .context("Failed to get social graph client from pool")?;

        let request = tonic::Request::new(GetFollowersRequest {
            req_id: 0, // In a real system, this would be a unique trace/request ID.
            user_id: msg.user_id,
            carrier: Default::default(), // Used for distributed tracing.
        });

        let followers = match social_graph_conn.get_followers(request).await {
            Ok(response) => response.into_inner().user_ids,
            Err(status) => {
                return Err(anyhow!("gRPC call to GetFollowers failed: {}", status));
            }
        };

        // 2. Combine followers and mentioned users.
        let mut user_ids_to_update: HashSet<i64> = followers.into_iter().collect();
        for mentioned_id in msg.user_mentions_id {
            user_ids_to_update.insert(mentioned_id);
        }

        if user_ids_to_update.is_empty() {
            warn!(
                "No followers or mentions for user_id {}, nothing to do.",
                msg.user_id
            );
            return Ok(());
        }

        // 3. Update Redis timelines.
        let mut redis_conn = redis_pool
            .get()
            .await
            .context("Failed to get Redis connection from pool")?;
        let mut pipe = redis::pipe();

        for user_id in &user_ids_to_update {
            pipe.zadd(user_id.to_string(), msg.post_id.to_string(), msg.timestamp);
        }

        pipe.query_async::<()>(&mut *redis_conn)
            .await
            .context("Redis pipeline command failed")?;

        info!(
            "Wrote post {} to timelines of {} users.",
            msg.post_id,
            user_ids_to_update.len()
        );

        Ok(())
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let subscriber = FmtSubscriber::builder()
        .with_max_level(Level::INFO)
        .finish();
    tracing::subscriber::set_global_default(subscriber).expect("setting default subscriber failed");

    let config = Arc::new(config::load_config().context("Failed to load configuration")?);
    info!("Configuration loaded successfully.");

    // --- Create Connection Pools ---

    // 1. Redis Pool
    let redis_addr = format!("redis://{}:{}/", config.redis.addr, config.redis.port);
    let redis_manager = bb8_redis::RedisConnectionManager::new(redis_addr.as_str())?;
    let redis_pool = bb8::Pool::builder()
        .max_size(config.redis.connections)
        .build(redis_manager)
        .await
        .context("Failed to create Redis pool")?;
    info!("Redis connection pool created.");

    // 2. Social Graph Service gRPC Pool
    let sg_addr = format!(
        "http://{}:{}",
        config.social_graph_service.addr, config.social_graph_service.port
    );
    let sg_manager = social_graph_client::SocialGraphConnectionManager { addr: sg_addr };
    let social_graph_pool = bb8::Pool::builder()
        .max_size(config.social_graph_service.connections)
        .build(sg_manager)
        .await
        .context("Failed to create Social Graph Service pool")?;
    info!("Social Graph Service connection pool created.");

    // --- Spawn Worker Tasks ---
    let mut worker_handles: Vec<JoinHandle<Result<()>>> = Vec::new();
    for i in 0..config.service.workers {
        let worker_config = Arc::clone(&config);
        let worker_redis_pool = redis_pool.clone();
        let worker_sg_pool = social_graph_pool.clone();

        let handle = tokio::spawn(async move {
            run_worker(i, worker_config, worker_redis_pool, worker_sg_pool).await
        });
        worker_handles.push(handle);
    }
    info!("Spawned {} worker tasks.", config.service.workers);

    // --- Wait for shutdown signal (Ctrl-C) ---
    tokio::select! {
        _ = tokio::signal::ctrl_c() => {
            info!("Ctrl-C received, shutting down.");
        }
        res = async {
            for handle in worker_handles {
                if let Err(e) = handle.await {
                    return Some(e)
                }
            }
            None
        } => {
            if let Some(e) = res {
                 error!("A worker task panicked or was cancelled: {:?}", e);
            }
        }
    }

    Ok(())
}
