syntax = "proto3";

package bridge;

service Worker {
  rpc SayHelloI1(HelloRequest) returns (HelloReply) {}
  rpc SayHelloI2(HelloRequest) returns (HelloReply) {}
  rpc SayHelloI3(HelloRequest) returns (HelloReply) {}
  rpc SayHelloI4(HelloRequest) returns (HelloReply) {}
}

message HelloRequest { string name = 1; }

message HelloReply { string message = 1; }

service TungChung {
  rpc SayFrontend(WalkRequest) returns (WalkReply) {}
  rpc SaySearch(WalkRequest) returns (WalkReply) {}
  rpc SayProfile(WalkRequest) returns (WalkReply) {}
  rpc SayGeo(WalkRequest) returns (WalkReply) {}
  rpc SayRate(WalkRequest) returns (WalkReply) {}
}

message WalkRequest { string name = 1; }

message WalkReply { string message = 1; }
