syntax = "proto3";

package hello;

// The greeting service definition.
service Greeter {
  // SayHello generates a hello message
  rpc SayHello(HelloRequest) returns (HelloReply) {}
  // SayHola will call SayHello
  rpc SayHola(HelloRequest) returns (HelloReply) {}
  // SayGoodbye generates a goodbye message
  rpc SayGoodbye(HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest { string name = 1; }

// The response message containing the greetings
message HelloReply { string message = 1; }
