apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: profile-service
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-service
  template:
    metadata:
      labels:
        io.kompose.service: profile-service
    spec:
      containers:
        - image: dengwxn/hotel_profile:latest
          name: hotel-profile
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "1"
      restartPolicy: Always
