apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: profile-memcached
  name: profile-memcached
spec:
  ports:
    - name: "11004"
      port: 11004
      targetPort: 11004
  selector:
    io.kompose.service: profile-memcached
