apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rate-mongo
  name: rate-mongo
spec:
  ports:
    - name: "27003"
      port: 27003
      targetPort: 27003
  selector:
    io.kompose.service: rate-mongo
