apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rate-memcached
  name: rate-memcached
spec:
  ports:
    - name: "11003"
      port: 11003
      targetPort: 11003
  selector:
    io.kompose.service: rate-memcached
