apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: search-service
  name: search-service
spec:
  ports:
    - name: "8660"
      port: 8660
      targetPort: 8660
  selector:
    io.kompose.service: search-service
