apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: search-service
  name: search-service
spec:
  replicas: 6
  selector:
    matchLabels:
      io.kompose.service: search-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f containers+svcs.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: search-service
    spec:
      containers:
        - image: vicsli/hotel_search:latest
          name: hotel-search
          # imagePullPolicy: Never
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "1"
      restartPolicy: Always
