apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-mongo
  name: user-mongo
spec:
  ports:
    - name: "27006"
      port: 27006
      targetPort: 27006
  selector:
    io.kompose.service: user-mongo
