apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f containers+svcs.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "8660"
      port: 8660
      targetPort: 8660
  selector:
    io.kompose.service: user-service
