apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  replicas: ${REPLICAS_FRONTEND}
  selector:
    matchLabels:
      io.kompose.service: frontend-service
  template:
    metadata:
      labels:
        io.kompose.service: frontend-service
    spec:
      containers:
        - image: dengwxn/hotel_frontend:${TAG}
          name: hotel-frontend
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "4"
      restartPolicy: Always
