apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rate-service
  name: rate-service
spec:
  replicas: ${REPLICAS_RATE}
  selector:
    matchLabels:
      io.kompose.service: rate-service
  template:
    metadata:
      labels:
        io.kompose.service: rate-service
    spec:
      containers:
        - image: dengwxn/hotel_rate:${TAG}
          name: hotel-rate
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "1"
      restartPolicy: Always
