apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: reservation-service
  name: reservation-service
spec:
  replicas: ${REPLICAS_RESERVATION}
  selector:
    matchLabels:
      io.kompose.service: reservation-service
  template:
    metadata:
      labels:
        io.kompose.service: reservation-service
    spec:
      containers:
        - image: dengwxn/hotel_reservation:${TAG}
          name: hotel-reservation
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "1"
      restartPolicy: Always
