[package]
name = "socialnet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "textservice_server"
path = "src/text_service/main.rs"

[[bin]]
name = "textservice_client"
path = "src/text_service/client.rs"

[[bin]]
name = "usermention_server"
path = "src/user_mention/main.rs"

[[bin]]
name = "usermention_client"
path = "src/user_mention/client.rs"

[[bin]]
name = "url_shorten_server"
path = "src/url_shorten/main.rs"

[[bin]]
name = "url_shorten_client"
path = "src/url_shorten/client.rs"


[dependencies]
tonic = { path = "../../libs/tonic/tonic" }
prost = "0.12"
tokio = { path = "../../libs/tokio/tokio", features = ["full"] }
mongodb = { path = "../../3rd_party/mongodb" }
memcache = "0.16"
async-memcached = { path = "../../3rd_party/async-memcached" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
futures-lite = { version = "2.0.0" }
futures = "0.3"
rand = "0.8.5"  
log = "0.4"
env_logger = "0.10"
opentelemetry = { version = "0.20", features = ["trace"] }
tracing-opentelemetry = "0.20"
tracing = "0.1"
regex = "1.11.1"
async = "0.0.0"
chrono = "0.4.23"

[build-dependencies]
tonic-build = { path = "../../libs/tonic/tonic-build", features = ["prost"] }
