[package]
name = "socialnet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniqueid_server"
path = "src/unique_id/server.rs"

[[bin]]
name = "uniqueid_client"
path = "src/unique_id/client.rs"

[[bin]]
name = "media_server"
path = "src/media/main.rs"

[[bin]]
name = "media_client"
path = "src/media/client.rs"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { path = "../../libs/tokio/tokio", features = ["macros", "rt-multi-thread"] }
rand = "0.8.5"  
log = "0.4"
env_logger = "0.10"
opentelemetry = { version = "0.20", features = ["trace"] }
tracing-opentelemetry = "0.20"
tracing = "0.1"

[build-dependencies]
tonic-build = "0.12"
