services:
  # -------------------------------------------
  # Post Storage Section
  # -------------------------------------------
  post-storage-mongo:
    image: mongo:7.0
    container_name: "socialnet-post_storage_mongo"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - post_storage_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4"

  post-storage-memcached:
    image: memcached:1.6
    container_name: "socialnet-post_storage_memcached"
    restart: always
    networks:
      - socialnet-network
    deploy:
      resources:
        limits:
          cpus: "4"

  post-storage-service:
    image: post_storage_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=post_storage_server
      - POST_STORAGE_MONGODB_URI=mongodb://socialnet-post_storage_mongo:27017
      - POST_STORAGE_MONGODB_DATABASE=post-storage
      - POST_STORAGE_MEMCACHED_ADDR=tcp://socialnet-post_storage_memcached:11211
    depends_on:
      - post-storage-mongo
      - post-storage-memcached
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # User Timeline Section
  # -------------------------------------------
  user-timeline-mongo:
    image: mongo:7.0
    container_name: "socialnet-user_timeline_mongo"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - user_timeline_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "8"

  user-timeline-redis:
    image: redis:7.2
    container_name: "socialnet-user_timeline_redis"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - user_timeline_redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  user-timeline-service:
    image: user_timeline_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 4
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=user_timeline_server
      - USER_TIMELINE_MONGODB_URI=mongodb://socialnet-user_timeline_mongo:27017
      - USER_TIMELINE_REDIS_URL=redis://socialnet-user_timeline_redis:6379
      - POST_STORAGE_IP=socialnet-post-storage-service
      - POST_STORAGE_PORT=8080
      - POST_STORAGE_REPLICAS=1
    depends_on:
      - user-timeline-mongo
      - user-timeline-redis
      - post-storage-service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Home Timeline Section
  # -------------------------------------------
  home-timeline-redis:
    image: redis:7.2
    container_name: "socialnet-home_timeline_redis"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - home_timeline_redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  home-timeline-service:
    image: home_timeline_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=home_timeline_server
      - HOME_TIMELINE_REDIS_URL=redis://socialnet-home_timeline_redis:6379
      # - POST_STORAGE_SERVICE_ADDR=http://socialnet-post-storage-service:8080
      # - SOCIAL_GRAPH_SERVICE_ADDR=http://socialnet-social-graph-service:8080
      # Post Storage Config
      - POST_STORAGE_SERVICE_IP=socialnet-post-storage-service
      - POST_STORAGE_SERVICE_PORT=8080
      - POST_STORAGE_SERVICE_REPLICAS=1

      # Social Graph Config
      - SOCIAL_GRAPH_SERVICE_IP=socialnet-social-graph-service
      - SOCIAL_GRAPH_SERVICE_PORT=8080
      - SOCIAL_GRAPH_SERVICE_REPLICAS=1
    depends_on:
      - home-timeline-redis
      - post-storage-service
      - social-graph-service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  write-home-timeline-redis:
    image: redis:7.2
    container_name: "socialnet-write_home_timeline_redis"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - write_home_timeline_redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  write-home-timeline-service:
    image: write_home_timeline_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=write_home_timeline_server
      - RABBITMQ_URL=amqp://guest:guest@socialnet-rabbitmq:5672
      - REDIS_URL=redis://socialnet-write_home_timeline_redis:6379
      # - SOCIAL_GRAPH_SERVICE_ADDR=http://socialnet-social-graph-service:8080
      # Social Graph Config
      - SOCIAL_GRAPH_SERVICE_IP=socialnet-social-graph-service
      - SOCIAL_GRAPH_SERVICE_PORT=8080
      - SOCIAL_GRAPH_SERVICE_REPLICAS=1
    depends_on:
      - rabbitmq
      - write-home-timeline-redis
      - social-graph-service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # User Service Section
  # -------------------------------------------
  user-mongo:
    image: mongo:7.0
    container_name: "socialnet-user_mongo"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - user_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4"

  user-redis:
    image: redis:7.2
    container_name: "socialnet-user_redis"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - user_redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  user-service:
    image: user_service:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: on-failure
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=user_service
      - MONGO_URL=mongodb://socialnet-user_mongo:27017/user
      - REDIS_URL=redis://socialnet-user_redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - MACHINE_ID=02
    depends_on:
      - user-mongo
      - user-redis
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Social Graph Section
  # -------------------------------------------
  social-graph-mongo:
    image: mongo:7.0
    container_name: "socialnet-social_graph_mongo"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - social_graph_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4"

  social-graph-redis:
    image: redis:7.2
    container_name: "socialnet-social_graph_redis"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - social_graph_redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  social-graph-service:
    image: social_graph_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=social_graph_server
      - MONGO_URL=mongodb://socialnet-social_graph_mongo:27017/social-graph
      - REDIS_URL=redis://socialnet-social_graph_redis:6379
      # - USER_SERVICE_ADDR=http://socialnet-user-service:8080
      # User Service Configuration
      - USER_SERVICE_IP=socialnet-user-service
      - USER_SERVICE_PORT=8080
      - USER_SERVICE_REPLICAS=1
    depends_on:
      - social-graph-mongo
      - social-graph-redis
      - user-service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Unique ID Section
  # -------------------------------------------
  unique-id-service:
    image: unique_id_service:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=unique_id_service
      - MACHINE_ID=01
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Media Section
  # -------------------------------------------
  media-service:
    image: media_service:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=media_service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Text Service Section
  # -------------------------------------------
  text-service:
    image: textservice_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    depends_on:
      - user-mention-service
      - url-shorten-service
    environment:
      - BINARY_NAME=textservice_server
      # - USER_MENTION_SERVICE_ADDR=http://socialnet-user-mention-service:8080
      # - URL_SHORTEN_SERVICE_ADDR=http://socialnet-url-shorten-service:8080
      - USER_MENTION_SERVICE_IP=socialnet-user-mention-service
      - USER_MENTION_SERVICE_PORT=8080
      - USER_MENTION_SERVICE_REPLICAS=1

      - URL_SHORTEN_SERVICE_IP=socialnet-url-shorten-service
      - URL_SHORTEN_SERVICE_PORT=8080
      - URL_SHORTEN_SERVICE_REPLICAS=1
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # User Mention Section
  # -------------------------------------------
  user-mention-mongo:
    image: mongo:7.0
    container_name: "socialnet-user_mention_mongo"
    restart: always
    networks:
      - socialnet-network
    volumes:
      - user_mention_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mention-memcached:
    image: memcached:1.6
    container_name: "socialnet-user_mention_memcached"
    restart: always
    networks:
      - socialnet-network
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mention-service:
    image: usermention_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=usermention_server
      - MONGO_URL=mongodb://socialnet-user_mention_mongo:27017/user-mention
      - MEMCACHED_URL=tcp://socialnet-user_mention_memcached:11211
    depends_on:
      - user-mention-mongo
      - user-mention-memcached
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # URL Shorten Section
  # -------------------------------------------
  url-shorten-mongo:
    image: mongo:7.0
    container_name: "socialnet-url_shorten_mongo"
    restart: always
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    networks:
      - socialnet-network
    volumes:
      - url_shorten_mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G

  url-shorten-service:
    image: url_shorten_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=url_shorten_server
      - MONGO_URL=mongodb://socialnet-url_shorten_mongo:27017/url-shorten
      - RUST_LOG=tonic=debug,info
    depends_on:
      - url-shorten-mongo
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Shared Infrastructure
  # -------------------------------------------
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: socialnet-rabbitmq
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - socialnet-network
    deploy:
      resources:
        limits:
          cpus: "4"

  # -------------------------------------------
  # Compose Post / Frontend / Gateway
  # -------------------------------------------
  compose-post-service:
    image: compose_post_server:${SOCIALNET_IMAGE_TAG:-latest}
    scale: 1
    restart: always
    ports:
      - "16987:8080"
    networks:
      - socialnet-network
    environment:
      - BINARY_NAME=compose_post_server

      - POST_STORAGE_IP=socialnet-post-storage-service
      - POST_STORAGE_PORT=8080
      - POST_STORAGE_REPLICAS=1

      - USER_TIMELINE_IP=socialnet-user-timeline-service
      - USER_TIMELINE_PORT=8080
      - USER_TIMELINE_REPLICAS=4

      - HOME_TIMELINE_IP=socialnet-home-timeline-service
      - HOME_TIMELINE_PORT=8080
      - HOME_TIMELINE_REPLICAS=1

      - USER_SERVICE_IP=socialnet-user-service
      - USER_SERVICE_PORT=8080
      - USER_SERVICE_REPLICAS=1

      - MEDIA_SERVICE_IP=socialnet-media-service
      - MEDIA_SERVICE_PORT=8080
      - MEDIA_SERVICE_REPLICAS=1

      - TEXT_SERVICE_IP=socialnet-text-service
      - TEXT_SERVICE_PORT=8080
      - TEXT_SERVICE_REPLICAS=1

      - USER_MENTION_SERVICE_IP=socialnet-user-mention-service
      - USER_MENTION_SERVICE_PORT=8080
      - USER_MENTION_SERVICE_REPLICAS=1

      - URL_SHORTEN_SERVICE_IP=socialnet-url-shorten-service
      - URL_SHORTEN_SERVICE_PORT=8080
      - URL_SHORTEN_SERVICE_REPLICAS=1

      - UNIQUE_ID_SERVICE_IP=socialnet-unique-id-service
      - UNIQUE_ID_SERVICE_PORT=8080
      - UNIQUE_ID_SERVICE_REPLICAS=1
    depends_on:
      - post-storage-service
      - user-timeline-service
      - home-timeline-service
      - user-service
      - unique-id-service
      - media-service
      - text-service
      - user-mention-service
      - url-shorten-service
    volumes:
      - ${APP_CONFIG_PATH}:/usr/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "4"

volumes:
  home_timeline_redis-data:
  social_graph_redis-data:
  user_redis-data:
  user_timeline_redis-data:
  write_home_timeline_redis-data:
  post_storage_mongo-data:
  social_graph_mongo-data:
  url_shorten_mongo-data:
  user_mongo-data:
  user_mention_mongo-data:
  user_timeline_mongo-data:
  rabbitmq-data:


networks:
  socialnet-network:
    name: socialnet-network
    driver: bridge