[package]
edition = "2021"
license = "MIT"
name = "reboot_hotel"
publish = false
version = "0.1.0"

[[bin]]
name = "hotel_client_bench"
path = "src/hotel/client/client_bench.rs"

[[bin]]
name = "hotel_client_lim"
path = "src/hotel/client/client_lim.rs"

[[bin]]
name = "hotel_client"
path = "src/hotel/client/client.rs"

[[bin]]
name = "hotel_frontend"
path = "src/hotel/frontend/main.rs"

[[bin]]
name = "hotel_geo"
path = "src/hotel/geo/main.rs"

[[bin]]
name = "hotel_rate"
path = "src/hotel/rate/main.rs"

[[bin]]
name = "hotel_search"
path = "src/hotel/search/main.rs"

[[bin]]
name = "hotel_profile"
path = "src/hotel/profile/main.rs"

[[bin]]
name = "recommendation-server"
path = "src/hotel/recommendation/main.rs"

[[bin]]
name = "recommendation-client"
path = "src/hotel/recommendation/client.rs"


[features]
prio_class = ["async-executor/prio_class", "tonic-masa/prio_class"]
prio_global = ["async-executor/prio_global", "tonic-masa/prio_global"]
prio_global_two = ["async-executor/prio_global_two", "tonic-masa/prio_global_two"]
prio_class_global = [
	"async-executor/prio_class_global",
	"tonic-masa/prio_class_global",
]
prio_local = ["async-executor/prio_local", "tonic-masa/prio_local"]
prio_local_two = ["async-executor/prio_local_two", "tonic-masa/prio_local_two"]
fifo_two = ["async-executor/fifo_two", "tonic-masa/fifo_two"]
fifo = ["async-executor/fifo", "tonic-masa/fifo"]

gcp = ["dep:prost-types", "tonic/tls"]
routeguide = [
	"dep:async-stream",
	"tokio-stream",
	"dep:rand",
	"dep:serde",
	"dep:serde_json",
]
reflection = ["dep:tonic-reflection"]
autoreload = ["tokio-stream/net", "dep:listenfd"]
health = ["dep:tonic-health"]
grpc-web = [
	"dep:tonic-web",
	"dep:bytes",
	"dep:http",
	"dep:hyper",
	"dep:tracing-subscriber",
	"dep:tower",
]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
hyper-warp = [
	"dep:either",
	"dep:tower",
	"dep:hyper",
	"dep:http",
	"dep:http-body",
	"dep:warp",
]
hyper-warp-multiplex = ["hyper-warp"]
uds = ["tokio-stream/net", "dep:tower", "dep:hyper"]
streaming = ["tokio-stream", "dep:h2"]
mock = ["tokio-stream", "dep:tower"]
tower = ["dep:hyper", "dep:tower", "dep:http"]
json-codec = ["dep:serde", "dep:serde_json", "dep:bytes"]
compression = ["tonic/gzip"]
tls = ["tonic/tls"]
tls-rustls = [
	"dep:hyper",
	"dep:hyper-rustls",
	"dep:tower",
	"tower-http/util",
	"tower-http/add-extension",
	"dep:rustls-pemfile",
	"dep:tokio-rustls",
]
dynamic-load-balance = ["dep:tower"]
timeout = ["tokio/time", "dep:tower"]
tls-client-auth = ["tonic/tls"]
types = ["dep:tonic-types"]
h2c = ["dep:hyper", "dep:tower", "dep:http"]
cancellation = ["dep:tokio-util"]

full = [
	"gcp",
	"routeguide",
	"reflection",
	"autoreload",
	"health",
	"grpc-web",
	"tracing",
	"hyper-warp",
	"hyper-warp-multiplex",
	"uds",
	"streaming",
	"mock",
	"tower",
	"json-codec",
	"compression",
	"tls",
	"tls-rustls",
	"dynamic-load-balance",
	"timeout",
	"tls-client-auth",
	"types",
	"cancellation",
	"h2c",
]
default = ["full"]

[dependencies]
# Reboot
tonic-masa = { path = "../tonic-masa" }
async-executor = { path = "../3rd_party/async-executor" }
async-compat = "0.2.3"
async-task = { path = "../3rd_party/async-task" }
smol = { path = "../3rd_party/smol" }
futures-lite = { version = "2.0.0" }
structopt = "0.3.23"
crossbeam-channel = "0.5"
mongodb = { path = "../3rd_party/mongodb" }
memcache = "0.16"
log = "0.4"
env_logger = "0.9"


# Common dependencies
tokio = { path = "../3rd_party/tokio/tokio", features = [
	"rt-multi-thread",
	"macros",
] }
prost = "0.12"
tonic = { path = "../tonic" }
futures = "0.3"
# Optional dependencies
tonic-web = { path = "../tonic-web", optional = true }
tonic-health = { path = "../tonic-health", optional = true }
tonic-reflection = { path = "../tonic-reflection", optional = true }
tonic-types = { path = "../tonic-types", optional = true }
either = { version = "1.9", optional = true }
async-stream = { version = "0.3", optional = true }
tokio-stream = { path = "../3rd_party/tokio/tokio-stream", optional = true }
tokio-util = { path = "../3rd_party/tokio/tokio-util", optional = true }
tower = { path = "../3rd_party/tower/tower", optional = true }
rand = { version = "0.8", optional = true }
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = [
	"tracing-log",
	"fmt",
], optional = true }
prost-types = { version = "0.12", optional = true }
http = { version = "0.2", optional = true }
http-body = { version = "0.4.2", optional = true }
hyper = { path = "../3rd_party/hyper", optional = true }
warp = { version = "0.3.4", default-features = false, optional = true }
listenfd = { version = "1.0", optional = true }
bytes = { version = "1", optional = true }
h2 = { path = "../3rd_party/h2", optional = true }
tokio-rustls = { path = "../3rd_party/tokio-rustls", optional = true }
hyper-rustls = { version = "0.24.0", features = ["http2"], optional = true }
rustls-pemfile = { version = "1", optional = true }
tower-http = { version = "0.4", optional = true }
anyhow = "1.0"
geo = "0.28"
# used by the geo service
kiddo = "4.2.1"


[build-dependencies]
tonic-build = { path = "../tonic-build", features = ["prost"] }
