[package]
edition = "2021"
license = "MIT"
name = "masa-integration-tests"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"
hyper = { path = "../../../hyper" }
tokio = { path = "../../../tokio/tokio", features = ["macros"] }
tonic = { path = "../../tonic" }
masa = { path = "../../../masa" }
masa-core = { path = "../../../masa-core" }
masa-policy = { path = "../../../masa-policy" }
http = { version = "0.2" }

[build-dependencies]
prost-build = "0.12"
tonic-build = { path = "../../tonic-build" }

[features]
default = []
sched_slo = ["masa/sched_slo"]
abort_slo = ["masa/abort_slo"]
abort_slack = ["masa/abort_slack"]
signal_slack = ["masa/signal_slack"]
ac_rajomon = ["masa/ac_rajomon"]
trace_queue_latency = ["masa/trace_queue_latency", "masa-policy/trace_queue_latency"]
