[package]
edition = "2021"
license = "MIT"
name = "masa-integration-tests"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"
async-executor = { path = "../../../async-executor" }
hyper = { path = "../../../hyper" }
tokio = { path = "../../../tokio/tokio", features = ["macros"] }
tonic = { path = "../../tonic" }
masa = { path = "../../../masa" }
http = { version = "0.2" }

[build-dependencies]
prost-build = "0.12"
tonic-build = { path = "../../tonic-build" }
