syntax = "proto3";

package frontend;

service Frontend {
  rpc HandleSearch(SearchRequest) returns (SearchResponse) {}
}

message SearchRequest {
  float lat = 1;
  float lon = 2;
  string inDate = 3;
  string outDate = 4;
  optional string locale = 5;
}

message SearchResponse { repeated Hotel hotels = 1; }

message Hotel {
  string name = 1;
  string id = 2;
  string phoneNumber = 3;
  float lat = 4;
  float lon = 5;
}

// message Address {
//   string streetNumber = 1;
//   string streetName = 2;
//   string city = 3;
//   string state = 4;
//   string country = 5;
//   string postcalCode = 6;
//   float lat = 7;
//   float lon = 8;
// }

// message Image { string url = 1; }
