services:
  rate-mongo:
    image: mongo:7.0
    container_name: "rate_mongo"
    command: --port 27003
    network_mode: "host"
    restart: always
    volumes:
      - rate:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-memcached:
    image: memcached:1.6
    container_name: "rate_memcached"
    command: --port 11003
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-mongo:
    image: mongo:7.0
    container_name: "profile_mongo"
    command: --port 27004
    network_mode: "host"
    restart: always
    volumes:
      - profile:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-memcached:
    image: memcached:1.6
    container_name: "profile_memcached"
    command: --port 11004
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-mongo:
    image: mongo:7.0
    container_name: "reservation_mongo"
    command: --port 27005
    network_mode: "host"
    restart: always
    volumes:
      - reservation:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-memcached:
    image: memcached:1.6
    container_name: "reservation_memcached"
    command: --port 11005
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mongo:
    image: mongo:7.0
    container_name: "user_mongo"
    command: --port 27006
    network_mode: "host"
    restart: always
    volumes:
      - user:/data
    deploy:
      resources:
        limits:
          cpus: "4"

volumes:
  rate:
  profile:
  reservation:
  user:
