services:
  rate-mongo:
    image: mongo:7.0
    container_name: "rate_mongo"
    command: --port 27003
    restart: always
    networks:
      - hotel_network
    volumes:
      - rate:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-memcached:
    image: memcached:1.6
    container_name: "rate_memcached"
    command: --port 11003 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-service:
    image: hotel_rate:latest
    container_name: "hotel_rate"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - rate-mongo
      - rate-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-mongo:
    image: mongo:7.0
    container_name: "profile_mongo"
    command: --port 27004
    restart: always
    networks:
      - hotel_network
    volumes:
      - profile:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-memcached:
    image: memcached:1.6
    container_name: "profile_memcached"
    command: --port 11004 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-service:
    image: hotel_profile:latest
    container_name: "hotel_profile"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - profile-mongo
      - profile-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-mongo:
    image: mongo:7.0
    container_name: "reservation_mongo"
    command: --port 27005
    restart: always
    networks:
      - hotel_network
    volumes:
      - reservation:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-memcached:
    image: memcached:1.6
    container_name: "reservation_memcached"
    command: --port 11005 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-service:
    image: hotel_reservation:latest
    container_name: "hotel_reservation"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - reservation-mongo
      - reservation-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mongo:
    image: mongo:7.0
    container_name: "user_mongo"
    command: --port 27006
    restart: always
    networks:
      - hotel_network
    volumes:
      - user:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  user-service:
    image: hotel_user:latest
    container_name: "hotel_user"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - user-mongo
    deploy:
      resources:
        limits:
          cpus: "4"

  geo-service:
    image: hotel_geo:latest
    container_name: "hotel_geo"
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  search-service:
    image: hotel_search:latest
    container_name: "hotel_search"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - geo-service
      - rate-service
    deploy:
      resources:
        limits:
          cpus: "4"

  frontend-service:
    image: hotel_frontend:latest
    container_name: "hotel_frontend"
    restart: always
    networks:
      - hotel_network
    ports:
      - "8660:8660"
    depends_on:
      - user-service
      - reservation-service
      - profile-service
      - rate-service
      - geo-service
      - search-service
    deploy:
      resources:
        limits:
          cpus: "4"
volumes:
  rate:
  profile:
  reservation:
  user:

networks:
 - hotel_network
