syntax = "proto3";

package child;

service Child {
  rpc RandomLatency(RandomLatencyRequest) returns (RandomLatencyResponse) {}
  rpc ConstantLatency(ConstantLatencyRequest)
      returns (ConstantLatencyResponse) {}
  rpc Presampled(PresampledRequest) returns (PresampledResponse) {}
  rpc Traced(TracedRequest) returns (TracedResponse) {}
}

message RandomLatencyRequest { uint64 sent_at = 1; }
message RandomLatencyResponse {
  uint64 queueing_latency = 1;
  uint64 sleep_latency = 2;
  uint64 handler_latency = 3;
}

message ConstantLatencyRequest { uint64 sent_at = 1; }
message ConstantLatencyResponse {
  uint64 queueing_latency = 1;
  uint64 handler_latency = 2;
  uint64 finished_at = 3;
}

message PresampledRequest {
  Latency latency = 1;
  double sleep = 2;
}
message PresampledResponse {}

message Latency {
  oneof latency_type {
    Fixed fixed = 1;
    Periodic periodic = 2;
  }
}

message Fixed {
  uint64 latency = 1;
}

message Periodic {
  uint64 slow_latency = 1;
  uint64 fast_latency = 2;
  uint32 slow_duration_ms = 3;
}

message TracedRequest { uint64 req_id = 1; }
message TracedResponse {}
