[package]
name = "generic-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
futures = "0.3.31"
ordered-float = "5.0.0"
prost = "0.12"
prost-types = "0.12"
rand = "0.9.0"
rand_distr = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { path = "../../../libs/tokio/tokio", features = ["full"] }
tonic = { path = "../../../libs/tonic/tonic" }

[build-dependencies]
tonic-build = { path = "../../../libs/tonic/tonic-build" }
