[package]
name = "generic-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
futures = "0.3.31"
prost = "0.12"
prost-types = "0.12"
rand = "0.9.0"
rand_distr = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { path = "../../../libs/tokio/tokio", features = ["full"] }
tonic = { path = "../../../libs/tonic/tonic" }
sim-config = { path = "../sim-config" }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
masa = { path = "../../../libs/masa/" }

[build-dependencies]
tonic-build = { path = "../../../libs/tonic/tonic-build" }
protoc-bin-vendored = "3"

[dev-dependencies]
tempfile = "3.13.0"

[[bin]]
name = "mssim-loadgen"
path = "src/loadgen.rs"

[features]
early = [
    "masa/early",
    "tonic/early",
]

fifo = ["tokio/fifo", "masa/fifo", "tonic/fifo"]

prio_global = [
  "tokio/prio_global",
  "masa/prio_global",
  "tonic/prio_global",
]
