# Use a recent Rust version for building
FROM rust:latest AS rust_builder

WORKDIR /app

# Install protobuf-compiler and other essential tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    protobuf-compiler \
    libprotobuf-dev \
    build-essential \
    pkg-config \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN rustup override set nightly

# We need to copy the entire project (from workspace root)
# This is because we want to link the generic-service with our runtime,
# as well as other crates (e.g., sim-config)
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY 3rd_party 3rd_party
COPY apps apps
COPY libs libs
COPY trace-analysis /trace-analysis

# Build the generic service
RUN cargo build --release --bin mssim-loadgen --features

# Command to run the load generator
CMD ["cargo", "run", "--release", "--bin", "mssim-loadgen"]
