[package]
name = "masa"
version = "0.1.0"
edition = "2021"

[dependencies]
masa-core = { path = "../masa-core" }
masa-policy = { path = "../masa-policy" }
tokio = { path = "../tokio/tokio", optional = true }
tonic = { path = "../tonic/tonic" }


[features]
sched_slo = ["masa-core/sched_slo", "tokio/sched_prio", "tonic/sched_slo", "masa-policy/sched_slo"]
sched_tailclipper = ["masa-core/sched_tailclipper", "tokio/sched_prio", "tokio/tailclipper", "tonic/sched_tailclipper", "masa-policy/sched_tailclipper"]
sched_fifo  = ["masa-core/sched_fifo",  "tokio/sched_fifo",  "tonic/sched_fifo", "masa-policy/sched_fifo"]
sched_pred = ["masa-core/sched_pred", "tonic/sched_pred", "sched_slo", "masa-policy/sched_pred"]

slo_abort = ["masa-core/slo_abort", "tonic/slo_abort", "masa-policy/slo_abort"]
estimator = ["masa-core/estimator", "tonic/estimator", "masa-policy/estimator"]

est_rms = ["tonic/est_rms", "masa-policy/est_rms"]
est_hist = ["tonic/est_hist", "masa-policy/est_hist"]
est_mean_var = ["tonic/est_mean_var", "masa-policy/est_mean_var"]

ac_pred = ["masa-core/ac_pred", "tonic/ac_pred", "masa-policy/ac_pred"]
ac_rajomon = ["masa-core/ac_rajomon", "tonic/ac_rajomon", "masa-policy/ac_rajomon"]
trace-queue = ["tonic/trace-queue", "masa-policy/trace-queue"]
