[package]
name = "masa-core"
version = "0.1.0"
edition = "2021"

[features]
sched_fifo = []
sched_prio = []
tailclipper = ["sched_prio"]
slo_abort = []
est_abort = ["slo_abort"]
est_mean_var = []
est_rms = []
est_hist = []
ac_est = ["slo_abort"]
ac_rajomon = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
base64 = "0.21"
log = "0.4"
http = "0.2"
