[package]
edition = "2021"
license = "MIT"
name = "hotel"
publish = false
version = "0.1.0"

[[bin]]
name = "hotel_client_bench"
path = "src/client/client_bench.rs"

[[bin]]
name = "hotel_frontend"
path = "src/frontend/main.rs"

[[bin]]
name = "hotel_geo"
path = "src/geo/main.rs"

[[bin]]
name = "hotel_rate"
path = "src/rate/main.rs"

[[bin]]
name = "hotel_review"
path = "src/review/main.rs"

[[bin]]
name = "hotel_search"
path = "src/search/main.rs"

[[bin]]
name = "hotel_profile"
path = "src/profile/main.rs"

[[bin]]
name = "hotel_reservation"
path = "src/reservation/main.rs"

[[bin]]
name = "hotel_user"
path = "src/user/main.rs"

[[bin]]
name = "hotel_recommendation"
path = "src/recommendation/main.rs"

# [[bin]]
# name = "recommendation-client"
# path = "src/recommendation/client.rs"

[[bin]]
name = "loadgen"
path = "src/loadgen/main.rs"

[features]
prio_class = [
  "tokio/prio_class",
  "masa/prio_class",
  "tonic/prio_class",
]
prio_global = [
  "tokio/prio_global",
  "masa/prio_global",
  "tonic/prio_global",
]
prio_global_early = [
  "tokio/prio_global_early",
  "masa/prio_global_early",
  "tonic/prio_global_early",
]
prio_class_global = [
  "tokio/prio_class_global",
  "masa/prio_class_global",
  "tonic/prio_class_global",
]
prio_local = [
  "tokio/prio_local",
  "masa/prio_local",
  "tonic/prio_local",
]
prio_local_early = [
  "tokio/prio_local_early",
  "masa/prio_local_early",
  "tonic/prio_local_early",
]
prio_local_direct = [
  "tokio/prio_local_direct",
  "masa/prio_local_direct",
  "tonic/prio_local_direct",
]
prio_local_indirect = [
  "tokio/prio_local_indirect",
  "masa/prio_local_indirect",
  "tonic/prio_local_indirect",
]
perfect_lsf = [
  "tokio/perfect_lsf",
  "masa/perfect_lsf",
  "tonic/perfect_lsf",
]
fifo = ["tokio/fifo", "masa/fifo", "tonic/fifo"]
fifo_early = [
  "tokio/fifo_early",
  "masa/fifo_early",
  "tonic/fifo_early",
]
fifo_infra = [
  "tokio/fifo_infra",
  "masa/fifo_infra",
  "tonic/fifo_infra",
]

fifo_span_tracing = [
  "tokio/fifo_span_tracing",
  "masa/fifo_span_tracing",
  "tonic/fifo_span_tracing",
]

fifo_queue_tracing = [
  "tokio/fifo_queue_tracing",
  "masa/fifo_queue_tracing",
  "tonic/fifo_queue_tracing",
]

prio_global_queue_tracing = [
  "tokio/prio_global_queue_tracing",
  "masa/prio_global_queue_tracing",
  "tonic/prio_global_queue_tracing",
]

synthetic = []
workload_stats = []

gcp = ["dep:prost-types", "tonic/tls"]
routeguide = [
	"dep:async-stream",
	"tokio-stream",
	"dep:rand",
	"dep:serde",
	"dep:serde_json",
]
reflection = ["dep:tonic-reflection"]
autoreload = ["tokio-stream/net", "dep:listenfd"]
health = ["dep:tonic-health"]
grpc-web = [
	"dep:tonic-web",
	"dep:bytes",
	"dep:http",
	"dep:hyper",
	"dep:tracing-subscriber",
	"dep:tower",
]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
hyper-warp = [
	"dep:either",
	"dep:tower",
	"dep:hyper",
	"dep:http",
	"dep:http-body",
	"dep:warp",
]
hyper-warp-multiplex = ["hyper-warp"]
uds = ["tokio-stream/net", "dep:tower", "dep:hyper"]
streaming = ["tokio-stream", "dep:h2"]
mock = ["tokio-stream", "dep:tower"]
tower = ["dep:hyper", "dep:tower", "dep:http"]
json-codec = ["dep:serde", "dep:serde_json", "dep:bytes"]
compression = ["tonic/gzip"]
tls = ["tonic/tls"]
tls-rustls = [
	"dep:hyper",
	"dep:hyper-rustls",
	"dep:tower",
	"tower-http/util",
	"tower-http/add-extension",
	"dep:rustls-pemfile",
	"dep:tokio-rustls",
]
dynamic-load-balance = ["dep:tower"]
timeout = ["tokio/time", "dep:tower"]
tls-client-auth = ["tonic/tls"]
types = ["dep:tonic-types"]
h2c = ["dep:hyper", "dep:tower", "dep:http"]
cancellation = ["dep:tokio-util"]

full = [
	"gcp",
	"routeguide",
	"reflection",
	"autoreload",
	"health",
	"grpc-web",
	"tracing",
	"hyper-warp",
	"hyper-warp-multiplex",
	"uds",
	"streaming",
	"mock",
	"tower",
	"json-codec",
	"compression",
	"tls",
	"tls-rustls",
	"dynamic-load-balance",
	"timeout",
	"tls-client-auth",
	"types",
	"cancellation",
	"h2c",
]
default = ["full"]

[dependencies]
# Reboot
masa = { path = "../../libs/masa" }
app-utils = { path = "../app-utils" }
app-util-macros = { path = "../app-util-macros" }
async-compat = "0.2.3"
futures-lite = { version = "2.0.0" }
structopt = "0.3.23"
crossbeam-channel = "0.5"
mongodb = { version = "=2.8.2" }
memcache = "0.16"
async-memcached = { path = "../../3rd_party/async-memcached" }
log = "0.4"
# Common dependencies
tokio = { path = "../../libs/tokio/tokio", features = [
	"rt-multi-thread",
	"macros",
] }
prost = "0.12"
tonic = { path = "../../libs/tonic/tonic" }
futures = "0.3"
# Optional dependencies
tonic-web = { path = "../../libs/tonic/tonic-web", optional = true }
tonic-health = { path = "../../libs/tonic/tonic-health", optional = true }
tonic-reflection = { path = "../../libs/tonic/tonic-reflection", optional = true }
tonic-types = { path = "../../libs/tonic/tonic-types", optional = true }
either = { version = "1.9", optional = true }
async-stream = { version = "0.3", optional = true }
tokio-stream = { path = "../../libs/tokio/tokio-stream", optional = true }
tokio-util = { path = "../../libs/tokio/tokio-util", optional = true }
tower = { path = "../../libs/tower/tower", optional = true }
rand = { version = "0.8", optional = true }
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = [
	"tracing-log",
	"fmt",
], optional = true }
prost-types = { version = "0.12", optional = true }
http = { version = "0.2", optional = true }
http-body = { version = "0.4.2", optional = true }
hyper = { path = "../../libs/hyper", optional = true }
warp = { version = "0.3.4", default-features = false, optional = true }
listenfd = { version = "1.0", optional = true }
bytes = { version = "1", optional = true }
h2 = { version = "0.3.27", optional = true }
tokio-rustls = { path = "../../3rd_party/tokio-rustls", optional = true }
hyper-rustls = { version = "0.24.0", features = ["http2"], optional = true }
rustls-pemfile = { version = "1", optional = true }
tower-http = { version = "0.4", optional = true }
anyhow = "1.0"
geo = "0.28"
# used by the geo service
kiddo = "4.2.1"
# used by reservation service
chrono = "0.4.38"
clap = { version = "4.4", features = ["derive"] }


[build-dependencies]
tonic-build = { path = "../../libs/tonic/tonic-build", features = ["prost"] }

[patch.crates-io]
tokio = { path = "./libs/tokio/tokio", version = "1" }

