FROM rustlang/rust:nightly-slim AS builder

ARG FEATURES

RUN apt-get update
RUN apt-get install -y\
        curl\
        unzip\
        protobuf-compiler\
        pkg-config\
        libssl-dev

# Create a new empty shell project
WORKDIR /usr/src/app
RUN cargo init

# Copy over dependencies and libs.
# Order these from least to most likely to be modified.
COPY Cargo.toml Cargo.lock* ./
COPY 3rd_party ./3rd_party
COPY libs ./libs

COPY apps/hotel/Cargo.toml ./apps/hotel/Cargo.toml
COPY apps/socialnet/Cargo.toml ./apps/socialnet/Cargo.toml

WORKDIR /usr/src/app/apps/hotel
RUN mkdir src
RUN touch src/lib.rs

# Build the dependencies first. This will be cached.
RUN if [ -z "$FEATURES" ]; then\
  cargo build --release --lib;\
else \
  cargo build --release --lib --features ${FEATURES};\
fi
WORKDIR /usr/src/app/

# build every service in hotel
# Note: we build every service once here. They're cached then reused when we
# generate per-service image in the second stage below.
COPY apps ./apps
WORKDIR /usr/src/app/apps/hotel
RUN if [ -z "$FEATURES" ]; then\
  cargo build --release;\
else \
  cargo build --release --features ${FEATURES};\
fi


# Final stage - create a slimmer image
FROM debian:bookworm-slim

ARG BINARY_NAME
RUN if [ -z "$BINARY_NAME" ]; then \
    echo "Error: BINARY_NAME argument is required" && exit 1; \
    fi

# Copy the built executable from the builder stage
COPY --from=builder /usr/src/app/target/release/${BINARY_NAME} /usr/local/bin/${BINARY_NAME}

# Set the command to run your application
CMD ["${BINARY_NAME}"]
