services:
  rate-mongo:
    image: mongo:7.0
    container_name: "rate_mongo"
    command: --port 27003
    # network_mode: "host"
    ports:
      - "27003:27003"
    restart: always
    volumes:
      - rate:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-memcached:
    image: memcached:1.6
    container_name: "rate_memcached"
    command: --port 11003 --threads 4
    # network_mode: "host"
    ports:
      - "11003:11003"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-mongo:
    image: mongo:7.0
    container_name: "profile_mongo"
    command: --port 27004
    # network_mode: "host"
    ports:
      - "27004:27004"
    restart: always
    volumes:
      - profile:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-memcached:
    image: memcached:1.6
    container_name: "profile_memcached"
    command: --port 11004 --threads 4
    # network_mode: "host"
    ports:
      - "11004:11004"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-mongo:
    image: mongo:7.0
    container_name: "reservation_mongo"
    command: --port 27005
    # network_mode: "host"
    ports:
      - "27005:27005"
    restart: always
    volumes:
      - reservation:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-memcached:
    image: memcached:1.6
    container_name: "reservation_memcached"
    command: --port 11005 --threads 4
    # network_mode: "host"
    ports:
      - "11005:11005"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mongo:
    image: mongo:7.0
    container_name: "user_mongo"
    command: --port 27006
    # network_mode: "host"
    ports:
      - "27006:27006"
    restart: always
    volumes:
      - user:/data
    deploy:
      resources:
        limits:
          cpus: "4"

          #   review-mongo:
          #     image: mongo:7.0
          #     container_name: "review_mongo"
          #     command: --port 27007
          #     network_mode: "host"
          #     restart: always
          #     volumes:
          #       - review:/data
          #     deploy:
          #       resources:
          #         limits:
          #           cpus: "4"
          # 
          #   review-memcached:
          #     image: memcached:1.6
          #     container_name: "review_memcached"
          #     command: --port 11006 --threads 4
          #     network_mode: "host"
          #     restart: always
          #     deploy:
          #       resources:
          #         limits:
          #           cpus: "4"

volumes:
  rate:
  profile:
  reservation:
  user:
