services:
  rate-mongo:
    image: mongo:7.0
    container_name: "${CONTAINER_PREFIX:-}rate_mongo"
    command: --port 27003
    restart: always
    networks:
      - hotel_network
    volumes:
      - rate:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-memcached:
    image: memcached:1.6
    container_name: "${CONTAINER_PREFIX:-}rate_memcached"
    command: --port 11003 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  rate-service:
    image: hotel_rate:latest
    scale: ${RATE_REPLICAS}
    restart: always
    networks:
      - hotel_network
    depends_on:
      - rate-mongo
      - rate-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-mongo:
    image: mongo:7.0
    container_name: "${CONTAINER_PREFIX:-}profile_mongo"
    command: --port 27004
    restart: always
    networks:
      - hotel_network
    volumes:
      - profile:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-memcached:
    image: memcached:1.6
    container_name: "${CONTAINER_PREFIX:-}profile_memcached"
    command: --port 11004 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  profile-service:
    image: hotel_profile:latest
    scale: ${PROFILE_REPLICAS}
    restart: always
    networks:
      - hotel_network
    depends_on:
      - profile-mongo
      - profile-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-mongo:
    image: mongo:7.0
    container_name: "${CONTAINER_PREFIX:-}reservation_mongo"
    command: --port 27005
    restart: always
    networks:
      - hotel_network
    volumes:
      - reservation:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-memcached:
    image: memcached:1.6
    container_name: "${CONTAINER_PREFIX:-}reservation_memcached"
    command: --port 11005 --threads 4
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  reservation-service:
    image: hotel_reservation:latest
    scale: ${RESERVATION_REPLICAS}
    restart: always
    networks:
      - hotel_network
    depends_on:
      - reservation-mongo
      - reservation-memcached
    deploy:
      resources:
        limits:
          cpus: "4"

  user-mongo:
    image: mongo:7.0
    container_name: "${CONTAINER_PREFIX:-}user_mongo"
    command: --port 27006
    restart: always
    networks:
      - hotel_network
    volumes:
      - user:/data
    deploy:
      resources:
        limits:
          cpus: "4"

  user-service:
    image: hotel_user:latest
    scale: ${USER_REPLICAS}
    restart: always
    networks:
      - hotel_network
    depends_on:
      - user-mongo
    deploy:
      resources:
        limits:
          cpus: "4"

  geo-service:
    image: hotel_geo:latest
    scale: ${GEO_REPLICAS}
    restart: always
    networks:
      - hotel_network
    deploy:
      resources:
        limits:
          cpus: "4"

  search-service:
    image: hotel_search:latest
    scale: ${SEARCH_REPLICAS}
    restart: always
    networks:
      - hotel_network
    depends_on:
      - geo-service
      - rate-service
    deploy:
      resources:
        limits:
          cpus: "4"

  hotel-frontend-service:
    image: hotel_frontend:latest
    container_name: "${CONTAINER_PREFIX:-}hotel_frontend"
    restart: always
    networks:
      - hotel_network
    depends_on:
      - user-service
      - reservation-service
      - profile-service
      - rate-service
      - geo-service
      - search-service
    deploy:
      resources:
        limits:
          cpus: "4"
volumes:
  rate:
  profile:
  reservation:
  user:

networks:
  hotel_network:
    driver: bridge
