apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synthetic.fullname" . }}-config
  labels:
    {{- include "synthetic.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.appConfig | nindent 4 }}
