apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetic.fullname" . }}-frontend
  labels:
    {{- include "synthetic.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "synthetic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synthetic.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synthetic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ .Values.image.frontendName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BINARY_NAME
              value: synthetic_frontend
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: DOCKER_COMPOSE_PROJECT_NAME
              value: {{ include "synthetic.fullname" . | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/config.json
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: {{ include "synthetic.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
