[package]
name = "recommendation"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "recommendation-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "recommendation-client"
path = "src/client.rs"

[dependencies]
tonic = "0.12"
prost = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"  # For JSON serialization/deserialization (optional)
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
geo = "0.21"

[build-dependencies]
tonic-build = "0.12"
