apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  sessionAffinity: None
  ports:
    - name: "8660"
      port: 8660
      targetPort: 8660
  selector:
    io.kompose.service: frontend-service
