apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: geo-service
  name: geo-service
spec:
  replicas: ${REPLICAS_GEO}
  selector:
    matchLabels:
      io.kompose.service: geo-service
  template:
    metadata:
      labels:
        io.kompose.service: geo-service
    spec:
      containers:
        - image: dengwxn/hotel_geo:latest
          name: hotel-geo
          ports:
            - containerPort: 8660
              protocol: TCP
          resources:
            limits:
              cpu: "1"
      restartPolicy: Always
