apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: geo-service
  name: geo-service
spec:
  clusterIP: None
  ports:
    - name: "8660"
      port: 8660
      targetPort: 8660
  selector:
    io.kompose.service: geo-service
