apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: reservation-mongo
  name: reservation-mongo
spec:
  ports:
    - name: "27005"
      port: 27005
      targetPort: 27005
  selector:
    io.kompose.service: reservation-mongo
