syntax = "proto3";

package frontend;

service Frontend {
  rpc HandlePing(PingRequest) returns (PingResponse) {}
  rpc HandleSearch(SearchRequest) returns (SearchResponse) {}
  rpc HandleReservation(ReservationRequest) returns (ReservationResponse) {}
  rpc HandleReview(ReviewRequest) returns (ReviewResponse) {}
}

message PingRequest { string message = 1; }

message PingResponse { string message = 1; }

message SearchRequest {
  double lat = 1;
  double lon = 2;
  string inDate = 3;
  string outDate = 4;
  optional string locale = 5;
}

message SearchResponse { 
  repeated Hotel hotels = 1;
}

message Hotel {
  string name = 1;
  string id = 2;
  string phoneNumber = 3;
  float lat = 4;
  float lon = 5;
}

// message Address {
//   string streetNumber = 1;
//   string streetName = 2;
//   string city = 3;
//   string state = 4;
//   string country = 5;
//   string postcalCode = 6;
//   float lat = 7;
//   float lon = 8;
// }

// message Image { string url = 1; }

message ReservationRequest {
  string username = 1;
  string password = 2;
  string customer = 11;
  repeated string hotels = 12;
  string inDate = 13;
  string outDate = 14;
  uint32 numRooms = 15;
}

message ReservationResponse { repeated string hotels = 1; }

message ReviewRequest {
  string hotelId = 1;
}

message ReviewResponse {
  repeated ReviewComm reviews = 1;
}

message ReviewComm {
  string reviewId = 1;
  string hotelId = 2;
  string name = 3;
  float rating = 4;
  string description = 5;
  repeated Image images = 6;
}

message Image {
  string url = 1;
  bool default = 2;
}
