name: check-cargo

on:
  workflow_call:

env:
  CI: "true"

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - "sched_fifo"
          - "sched_slo"
          - "sched_tailclipper,abort_slo"
          - "sched_slo,ac_rajomon"
          - "sched_slo,ac_pred,est_mean_var"
          - "sched_pred,abort_slo,ac_pred,est_mean_var"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
      - name: Install protobuf
        run: sudo apt-get update -yqq && sudo apt-get install -y protobuf-compiler
      - run: ulimit -n 8192 && rustc --version && cargo --version
      - run: ./scripts/check.sh "${{ matrix.features }}"

  cargo-check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
      - name: Install protobuf
        run: sudo apt-get update -yqq && sudo apt-get install -y protobuf-compiler
      - run: ulimit -n 8192 && rustc --version && cargo --version
      - run: ./scripts/check.sh --tests ""
