name: check-cargo

on:
  workflow_call:

env:
  CI: "true"

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - features: ""
            cache_key: default
          - features: "sched_fifo"
            cache_key: sched-fifo
          - features: "sched_slo"
            cache_key: sched-slo
          - features: "sched_tailclipper,abort_slo"
            cache_key: sched-tailclipper-abort-slo
          - features: "sched_slo,ac_rajomon"
            cache_key: sched-slo-ac-rajomon
          - features: "sched_slo,ac_pred,est_mean_var"
            cache_key: sched-slo-ac-pred-est-mean-var
          - features: "sched_pred,abort_slo,ac_pred,est_mean_var"
            cache_key: sched-pred-abort-slo-ac-pred-est-mean-var
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-01-07
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.cache_key }}
          cache-on-failure: true
      - name: Install protobuf
        run: sudo apt-get update -yqq && sudo apt-get install -y protobuf-compiler
      - run: ulimit -n 8192 && rustc --version && cargo --version
      - run: ./scripts/check.sh "${{ matrix.features }}"

  cargo-check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-01-07
      - uses: Swatinem/rust-cache@v2
        with:
          key: check-tests
          cache-on-failure: true
      - name: Install protobuf
        run: sudo apt-get update -yqq && sudo apt-get install -y protobuf-compiler
      - run: ulimit -n 8192 && rustc --version && cargo --version
      - run: ./scripts/check.sh --tests ""
