[package]
name = "app-utils"
version = "0.1.0"
edition = "2021"

[features]
json-codec = ["dep:serde", "dep:serde_json", "dep:bytes"]
full = [
	"json-codec",
]
default = ["full"]

[dependencies]
masa = { path = "../../libs/masa" }
tokio = { path = "../../libs/tokio/tokio", features = ["full"] }
tokio-stream = { path = "../../libs/tokio/tokio-stream", features = ["full"] }
tonic = { path = "../../libs/tonic/tonic" }
tower = { path = "../../libs/tower/tower" }
async-memcached = { path = "../../3rd_party/async-memcached" }
rand = { version = "0.8" }
structopt = "0.3.23"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
bytes = { version = "1", optional = true }
log = "0.4"
env_logger = "0.9"
crossbeam-channel = "0.5"
anyhow = "1.0.100"
futures = "0.3.31"
k8s-openapi = { version = "0.26.0",  features = ["v1_30"] }
kube = { version = "2.0.1", features = ["runtime", "rustls-tls", "ring"] }
tracing = "0.1.41"

# Needed by kube
rustls = { version = "0.23.32", features = ["ring"] }
