[package]
name = "app-utils"
version = "0.1.0"
edition = "2021"

[features]
json-codec = ["dep:serde", "dep:serde_json", "dep:bytes"]
full = [
	"json-codec",
]
default = ["full"]
prio_oldest = ["masa/prio_oldest"]
rajomon = ["masa/rajomon", "tonic/rajomon"]
trace-queue = ["masa/trace-queue", "tonic/trace-queue"]

[dependencies]
masa = { path = "../../libs/masa" }
tokio = { path = "../../libs/tokio/tokio", features = ["full"] }
tonic = { path = "../../libs/tonic/tonic" }
tower = { path = "../../libs/tower/tower" }
async-memcached = "0.5.0"
rand = { version = "0.8" }
structopt = "0.3.23"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
bytes = { version = "1", optional = true }
log = "0.4"
env_logger = "0.9"
crossbeam-channel = "0.5"
